In [3]:
a = "shibataken"   # 文字列は""でも でも可’’
print("a:", a, type(a)) # aの中身と型を出力
a = 2019
print("a:",a, type(a)) # aの中身と型を出力 
b, c = 10, "創成課題"
print("year:"+ str(a) +" month:"+ str(b) +" class:"+ c) # 出力例1、str()でキャスト
print("year:{} month:{} class:{}".format(a,b,c)) # 出力例2

a: shibataken <class 'str'>
a: 2019 <class 'int'>
year:2019 month:10 class:創成課題
year:2019 month:10 class:創成課題


In [4]:
1-2
4*5
7/5   # 整数同士の除算でfloat型
7//5  # 切り捨て除算
7%5  # 剰余
3**3  # 累乗

27

In [7]:
# ビット演算
x = 10   # b(1010)
y = 9    # b(1001)
print(x<<1) # 左シフト =10100
print(x>>1) # 右シフト =101
print(x & y) # AND =1000
print(x | y) # OR =1011
print(x ^ y) # XOR
print(~x)  # NOT、反転

20
5
8
11
3
-11


In [8]:
machine_learning_list = ["Supervised", "Unsupervised", "Reinforcement"] #[]はリスト
print(machine_learning_list) # 全て出力
print(machine_learning_list[0]) # 0番目の値を出力
print(machine_learning_list[0:2]) # スライス[0:2]で0～1番目の値を出力
print(len(machine_learning_list)) # len()でサイズを取得
machine_learning_list.append("semi-supervised") # リストの末尾に追加
print(machine_learning_list) # 全て出力

['Supervised', 'Unsupervised', 'Reinforcement']
Supervised
['Supervised', 'Unsupervised']
3
['Supervised', 'Unsupervised', 'Reinforcement', 'semi-supervised']


In [9]:
machine_learning_list = ("Supervised", "Unsupervised", "Reinforcement") # ()タプル
print(machine_learning_list) # 全て出力print(machine_learning_list[0]) # 0番目の値を出力
print(machine_learning_list[0:2]) # スライス[0:2]で0～1番目の値を出力
print(len(machine_learning_list)) # len()でサイズを取得# ↓タプルは変更できないのでエラー
machine_learning_list[0] = "Semi supervised"

('Supervised', 'Unsupervised', 'Reinforcement')
('Supervised', 'Unsupervised')
3


TypeError: 'tuple' object does not support item assignment

In [10]:
animal_dict = {"Human":2, "Dog":4, "Spider":8} # {}は辞書型
print(animal_dict) # 全て出力
print(animal_dict["Dog"]) # キー”Dog”の値を出力
print(len(animal_dict)) # サイズを出力

{'Human': 2, 'Dog': 4, 'Spider': 8}
4
3


In [11]:
hungry = False # bool
sleepy = True # bool
print(hungry,sleepy) # 値の出力

False True


In [12]:
print(type(hungry)) # 型の確認

<class 'bool'>


In [14]:
loop = 10 # loop回数
sum = 0  # 0~loopの合計
for i in range(loop): # range回数分ループ  
    print("i:",i)  # インデント（半角空白2つ）でfor文内であることを示唆  
    sum += i  # sumにiを加算
print("sum:",sum)

i: 0
i: 1
i: 2
i: 3
i: 4
i: 5
i: 6
i: 7
i: 8
i: 9
sum: 45


In [15]:
evlist = [2,4,6,8,10] # 偶数のリスト
sum = 0  # 0~loopの合計
for e in evlist: # listのインデックス順に、eに代入  
    print("e:",e)  # インデント（半角空白2つ）でfor文内であることを示唆  
    sum += e  # sumにeを加算
print("sum:",sum)

e: 2
e: 4
e: 6
e: 8
e: 10
sum: 30


In [16]:
a = 10 # aの値、
if a == 10:   # (aは10)がTrueならば  
    print("if:",a)
elif a > 10: # aが10ではなく10より大きければ  
    print("elif:",a)
else: # その他 10より小さかったら
    print("else:",a)

if: 10


In [17]:
buf1, buf2 = "sousei", "kadai"
if buf1 == "sousei" and buf2 == "kadai": # andの例  
    print("if")
elif buf1 != "sousei" or buf2 != "kadai": # orの例  
    print("elif")

if


In [20]:
none = None
if none is None:  
    print("none is None")

none is None


In [25]:
A = 100 #グローバル変数
def Func(x,y): # Func関数  
    print(A) # グローバル変数の出力  
    xy_sum = x + y  
    xy_sub = x - y  
    print("A:",A) # グローバル変数の出力  
    return xy_sum, xy_sub # 返り値は複数可能、リスト等も可能

num1,num2 = 10,20
F1,F2 = Func(num1,num2)
print(F1,F2)

100
A: 100
30 -10


In [26]:
class MyClass(): # コンストラクタのみのサンプル    
    def __init__(self, value): # #初期化メソッドを定義、引数にname        
        self.name = value  # nameアトリビュートを追加
        myinstance = MyClass("nano") # インスタンスの作成
        print(myinstance.name) #nameの出力

In [27]:
class MyClass(): # コンストラクタのみのサンプル    
    def __init__(self, value): # #初期化メソッドを定義、引数にname        
        self.name = value  # nameアトリビュートを追加
        myinstance = MyClass("nano") # インスタンスの作成
        print(myinstance.name) #nameの出力

In [30]:
class Myclass():     
    def __init__(self, a,b,c):        
        self.num1 = a        
        self.num2 = b        
        self.num3 = c    
    def func_sum(self): # 加算メソッド        
        total = self.num1 + self.num2 + self.num3        
        return total    
    def func_sub(self): # 減算メソッド        
        sub = self.num1 - self.num2 - self.num3        
        return sub
myinstanceA = Myclass(1,2,3) # インスタンスAを作成
myinstanceB = Myclass(10,20,30) # インスタンスBを作成
calc1 = myinstanceA.func_sum() # インスタンスAでfunc_sum関数を実行
calc2 = myinstanceB.func_sub() # インスタンスBでfunc_sub関数を実行
print(calc1,calc2)

6 -40


In [108]:
import numpy as np # numpyをインポートし、npとして以後使用する
arr1 = [[1,2],[3,4],[5,6]]    #リスト1
arr2 = [[7,8],[9,10],[11,12]] #リスト2
res = arr1 + arr2 # リスト同士の加算
print("case list\n",res) # リストが連結している
arr1 = np.array(arr1) # arr1をnumpy配列化
arr2 = np.array(arr2) # arr2をnumpy配列化
print(arr1.shape) # shapeでnumpy配列の構造を出力できる
print("case numpy\n",arr1 + arr2) #行列の加算

case list
 [[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]]
(3, 2)
case numpy
 [[ 8 10]
 [12 14]
 [16 18]]


array([[-1.46385011, -0.87831007],
       [-0.29277002,  0.29277002],
       [ 0.87831007,  1.46385011]])

In [109]:
#4-3
print("1 の段\n")
for i in range(1,10):
    for k in range(1,10):
        print(i," x ",k ,"=",i*k)
        if k == 9:
            print('==============')
            if i+1 <10:
                print(i+1,"の段\n")
            

1 の段

1  x  1 = 1
1  x  2 = 2
1  x  3 = 3
1  x  4 = 4
1  x  5 = 5
1  x  6 = 6
1  x  7 = 7
1  x  8 = 8
1  x  9 = 9
2 の段

2  x  1 = 2
2  x  2 = 4
2  x  3 = 6
2  x  4 = 8
2  x  5 = 10
2  x  6 = 12
2  x  7 = 14
2  x  8 = 16
2  x  9 = 18
3 の段

3  x  1 = 3
3  x  2 = 6
3  x  3 = 9
3  x  4 = 12
3  x  5 = 15
3  x  6 = 18
3  x  7 = 21
3  x  8 = 24
3  x  9 = 27
4 の段

4  x  1 = 4
4  x  2 = 8
4  x  3 = 12
4  x  4 = 16
4  x  5 = 20
4  x  6 = 24
4  x  7 = 28
4  x  8 = 32
4  x  9 = 36
5 の段

5  x  1 = 5
5  x  2 = 10
5  x  3 = 15
5  x  4 = 20
5  x  5 = 25
5  x  6 = 30
5  x  7 = 35
5  x  8 = 40
5  x  9 = 45
6 の段

6  x  1 = 6
6  x  2 = 12
6  x  3 = 18
6  x  4 = 24
6  x  5 = 30
6  x  6 = 36
6  x  7 = 42
6  x  8 = 48
6  x  9 = 54
7 の段

7  x  1 = 7
7  x  2 = 14
7  x  3 = 21
7  x  4 = 28
7  x  5 = 35
7  x  6 = 42
7  x  7 = 49
7  x  8 = 56
7  x  9 = 63
8 の段

8  x  1 = 8
8  x  2 = 16
8  x  3 = 24
8  x  4 = 32
8  x  5 = 40
8  x  6 = 48
8  x  7 = 56
8  x  8 = 64
8  x  9 = 72
9 の段

9  x  1 = 9
9  x  2 = 18
9  x  3

In [57]:
kuku_table = []
#print("1 の段\n")
for i in range(1,10):
    for k in range(1,10):
        ans = i*k
        #print(i," x ",k ,"=",ans)
        kuku_table.append(ans)
#         if k == 9:
#             print('==============')
#             if i+1 <10:
#                 print(i+1,"の段\n")

In [58]:
print("kuku_table:",kuku_table)

kuku_table: [1, 2, 3, 4, 5, 6, 7, 8, 9, 2, 4, 6, 8, 10, 12, 14, 16, 18, 3, 6, 9, 12, 15, 18, 21, 24, 27, 4, 8, 12, 16, 20, 24, 28, 32, 36, 5, 10, 15, 20, 25, 30, 35, 40, 45, 6, 12, 18, 24, 30, 36, 42, 48, 54, 7, 14, 21, 28, 35, 42, 49, 56, 63, 8, 16, 24, 32, 40, 48, 56, 64, 72, 9, 18, 27, 36, 45, 54, 63, 72, 81]


In [62]:
kuku_table = []
#pprint(kuku_table)
for i in range(1,10):
    for k in range(1,10):
        ans = i*k
        #print(i," x ",k ,"=",ans)
        kuku_table.append(ans)
        kuku_table.append(i)
#         if k == 9:
#             print('==============')
#             if i+1 <10:
#                 print(i+1,"の段\n")

In [5]:
kuku_table = [[i*j for i in range(1,10)]for j in range(1,10)]

In [6]:
from pprint import pprint
pprint(kuku_table)

[[1, 2, 3, 4, 5, 6, 7, 8, 9],
 [2, 4, 6, 8, 10, 12, 14, 16, 18],
 [3, 6, 9, 12, 15, 18, 21, 24, 27],
 [4, 8, 12, 16, 20, 24, 28, 32, 36],
 [5, 10, 15, 20, 25, 30, 35, 40, 45],
 [6, 12, 18, 24, 30, 36, 42, 48, 54],
 [7, 14, 21, 28, 35, 42, 49, 56, 63],
 [8, 16, 24, 32, 40, 48, 56, 64, 72],
 [9, 18, 27, 36, 45, 54, 63, 72, 81]]


In [110]:
x = (arr1-np.mean(arr1))/np.std(arr1)
x

array([[-1.46385011, -0.87831007],
       [-0.29277002,  0.29277002],
       [ 0.87831007,  1.46385011]])